// Generated by CoffeeScript 2.5.1
(function() {
  var app, bodyParser, express, puppeteer;

  express = require("express");

  app = express();

  puppeteer = require("puppeteer");

  bodyParser = require("body-parser");

  app.use(bodyParser.urlencoded({
    extended: true
  }));

  console.log({
    extended: true
  });

  app.use(bodyParser.json());

  app.get("/", function(req, res) {
    console.log("a");
    return res.sendFile(__dirname + "/index.html");
  });

  app.post("/", function(req, res) {
    var asyncFunc1;
    if (!req.body.gameId) {
      return res.send("No game id.");
    }
    res.send(req.body);
    return asyncFunc1 = async function() {
      var browser, page;
      browser = (await puppeteer.launch({
        headless: false
      }));
      page = (await browser.newPage());
      return (await page.goto("https://blooket.com/play"));
    };
  });

  app.listen("3000", null);

}).call(this);
